### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by AsadNoman** [andaviaco/tblo#1]
I was hoping if you could just help me understand your code. I want to know what your abbreviated parameters stand for. Please reply ASAP, cause someone's fate depends on it.

**Comment by andaviaco** [comment]
@AsadNoman It's been a year since I coded this project, if I remember well, TBLO constructor requires these params:
```
npopulation = Number of learners in the population
ngenerations = Max number of generations/iterations
fn_eval = Evaluation function
fn_lb = Function lower bound
fn_ub = Upper bound
```
You can see examples in [main.py](https://github.com/andaviaco/tblo/blob/master/src/main.py#L6):
```
tblo_sphere = TBLO(500, 100, lib.sphere, fn_lb=[-5, -5], fn_ub=[5, 5])
min_x, min_y = tblo_sphere.optimize()
```
I would appreciate any help with the documentation. 😉

**Comment by AsadNoman** [comment]
Thanks. I really appreciate your response. 
One more thing, I was looking for the implementation of _Particle swarm optimization_ and _Ant colony optimization_ in python. I found out your implementation rather interesting one, and I was wondering if you have an implementation for these two as well.

**Comment by andaviaco** [comment]
Yes, I have those implementations too. Here:
[Particle Swarm Optimization](https://github.com/andaviaco/pso)
[Ant Colony Optimization](https://github.com/andaviaco/aco)

**Comment by AsadNoman** [comment]
Amazing. Thanks :)

**Comment by AsadNoman** [comment]
Reply to my email.
